{
  "code": 0,
  "is_server_open": true,
  "is_firewall_open": false,
  "cdn_url": "https://dl.cdn.freefiremobile.com/live/ABHotUpdates/",
  "backup_cdn_url": "https://dl.cdn.freefiremobile.com/live/ABHotUpdates/",
  "abhotupdate_cdn_url": "https://minnraiserver.vercel.app/hotpatchs/",
  "img_cdn_url": "https://minnraiserver.vercel.app",
  "login_download_optionalpack": "",
  "need_track_hotupdate": false,
  "abhotupdate_check": "cache_res;assetindexer;SH-Gpp",
  "latest_release_version": "OB54",
  "min_hint_size": 1,
  "space_required_in_GB": 1.48,
  "should_check_ab_load": false,
  "force_refresh_restype": "optionalavatarres",
  "remote_version": "2.127.16",
  "server_url": "https://loginbp.ggpolarbear.com/",
  "is_review_server": true,
  "use_login_optional_download": true,
  "use_background_download": false,
  "use_background_download_lobby": false,
  "country_code": "SG",
  "client_ip": "216.198.79.131",
  "gdpr_version": 0,
  "billboard_cdn_url": "https://dl.dir.freefiremobile.com/common/OB54/CSH/patchupdate/sgolzjifnmi101.ff_extend;https://dl.dir.freefiremobile.com/common/OB54/CSH/patchupdate/sgolzjifnmi102.ff_extend;https://dl.dir.freefiremobile.com/common/OB54/CSH/patchupdate/sgolzjifnmi103.ff_extend;https://dl.dir.freefiremobile.com/common/OB54/CSH/patchupdate/sgolzjifnmi104.ff_extend;https://dl.dir.freefiremobile.com/common/OB54/CSH/patchupdate/sgolzjifnmi105.ff_extend;https://dl.dir.freefiremobile.com/common/OB54/CSH/patchupdate/sgolzjifnmi106.ff_extend;https://dl.dir.freefiremobile.com/common/OB54/CSH/patchupdate/sgolzjifnmi107.ff_extend",
  "billboard_msg": "",
  "web_url": "",
  "billboard_bg_url": "https://dl.cdn.freefiremobile.com/common/OB23/version/Patch_Bg.png",
  "max_store": "",
  "max_web": "",
  "max_video": "",
  "patchnote_url": "https://dl.dir.freefiremobile.com/common/web_event/aswqooiwd/zClWsKYO.html?lang=en",
  "multi_region": "BD;IN;PK;VN;US;BR;EUROPE",
  "need_check_ip_list": [],
  "network_log_server": "https://minnraiserver.vercel.app",
  "web_log_server": "https://minnraiserver.vercel.app",
  "login_failed_count": 2,
  "test_url": "",
  "core_url": "ffp.springmusk.dev",
  "core_ip_list": [
    "0.0.0.0"
  ],
  "appstore_url": "http://play.google.com/store/apps/details?id=com.dts.freefiremax",
  "backup_appstore_url": "http://play.google.com/store/apps/details?id=com.dts.freefireth",
  "garena_login": true,
  "garena_hint": true,
  "gop_url": "",
  "gamevar": "var_name,comment,var_type,var_value\nvar_name,comment,\"var_type float, int, bool\",var_value\nFFAntihackDisabledRegions,关闭MTP的地区,string,\"IND,BD,NA\"\nFFAntihackDisabledClientVariant,FFAntihackDisabledClientVariant,string,\"ClientUsingVersion_MAX_HPE,ClientUsingVersion_FFI,ClientUsingVersion_NORMAL,ClientUsingVersion_MAX|IND,ClientUsingVersion_MAX|BD,ClientUsingVersion_NORMAL|BD\"\nEnableMtpLiteDataRegion,mtp轻特征开关,string,\"BR,EUROPE,ID,ME,US,RU,SAC,SG,TH,TW,VN,PK,ZA\"\nFFAntihackEmulatorCheckDisbaledClientVariant,FFAntihackEmulatorCheckDisbaledClientVariant,string,\"ClientUsingVersion_FFI,ClientUsingVersion_MAX,ClientUsingVersion_NORMAL\"\nForceTutorial_ChangeHudABTest,fps流程中打开hud选择界面的概率,float,-1\n",
  "remote_option_version": "optionallocres:50|optionalavatarres:708|optionalclothres:1150|optionalfootballres:47|optionalfullscreencgres:334|optionalhuntinggroundres:178|optionalinfection:121|optionalingameres:469|optionallobbyres:610|optionallonewolfres:77|optionallonewolfstrikeoutres:23|optionalludores:40|optionalmap1res:385|optionalmap2res:125|optionalmap4res:110|optionalmaphippores:90|optionalmapres:340|optionalnewblast:138|optionalpetres:848|optionalrushb:123|optionalrushingpetsres:88|optionalsnowduelres:59|optionaltrainingres:83|optionalugcres:537|optionalvoiceres:355|optionalwerewolves:173|optionalmapponyres:200|optionalsocialres:111|optionalwerunres:83|optionalugcoldparadiseres:32|optionalmultiregionres:25",
  "remote_option_version_astc": "optionallocres:50|optionalavatarres:711|optionalclothres:1150|optionalfootballres:38|optionalfullscreencgres:318|optionalhuntinggroundres:178|optionalinfection:116|optionalingameres:438|optionallobbyres:593|optionallonewolfres:139|optionallonewolfstrikeoutres:96|optionalludores:144|optionalmap1res:385|optionalmap2res:159|optionalmap4res:144|optionalmaphippores:92|optionalmapres:374|optionalnewblast:138|optionalpetres:848|optionalrushb:227|optionalrushingpetsres:192|optionalsnowduelres:59|optionaltrainingres:79|optionalugcres:507|optionalvoiceres:388|optionalwerewolves:277|optionalmapponyres:200|optionalsocialres:106|optionalwerunres:74|optionalugcoldparadiseres:32|optionalmultiregionres:26",
  "ggp_url": "ffp.springmusk.dev",
  "show_high_framerate_UI": true
}
