{
  "code": 0,
  "is_server_open": true,
  "is_firewall_open": false,
  "cdn_url": "http://187.77.225.94:2587/cdn/",
  "backup_cdn_url": "http://187.77.225.94:2587/cdn/",
  "abhotupdate_cdn_url": "http://187.77.225.94:2587/cdn/",
  "img_cdn_url": "https://dl.cdn.freefiremobile.com/common/",
  "login_download_optionalpack": "optionalclothres:shaders|optionalpetres:optionalpetres_commonab_shader|optionallobbyres:",
  "need_track_hotupdate": true,
  "abhotupdate_check": "cache_res;assetindexer;SH-Gpp",
  "latest_release_version": "OB54",
  "min_hint_size": 1,
  "space_required_in_GB": 1.48,
  "should_check_ab_load": false,
  "force_refresh_restype": "optionalavatarres",
  "remote_version": "2.127.16",
  "server_url": "https://loginbp.ggpolarbear.com/",
  "is_review_server": false,
  "use_login_optional_download": true,
  "use_background_download": false,
  "use_background_download_lobby": false,
  "country_code": "BR",
  "client_ip": "187.77.225.94",
  "gdpr_version": 0,
  "billboard_cdn_url": "https://dl.dir.freefiremobile.com/common/OB54/CSH/patchupdate/sgolzjifnmi101.ff_extend;https://dl.dir.freefiremobile.com/common/OB54/CSH/patchupdate/sgolzjifnmi102.ff_extend;https://dl.dir.freefiremobile.com/common/OB54/CSH/patchupdate/sgolzjifnmi103.ff_extend;https://dl.dir.freefiremobile.com/common/OB54/CSH/patchupdate/sgolzjifnmi104.ff_extend;https://dl.dir.freefiremobile.com/common/OB54/CSH/patchupdate/sgolzjifnmi105.ff_extend;https://dl.dir.freefiremobile.com/common/OB54/CSH/patchupdate/sgolzjifnmi106.ff_extend;https://dl.dir.freefiremobile.com/common/OB54/CSH/patchupdate/sgolzjifnmi107.ff_extend",
  "billboard_msg": "",
  "web_url": "",
  "billboard_bg_url": "https://dl.cdn.freefiremobile.com/common/OB23/version/Patch_Bg.png",
  "max_store": "",
  "max_web": "",
  "max_video": "",
  "patchnote_url": "https://dl.dir.freefiremobile.com/common/web_event/aswqooiwd/zClWsKYO.html?lang=en",
  "multi_region": "",
  "need_check_ip_list": [],
  "network_log_server": "https://sgnetwork.ggblueshark.com/",
  "web_log_server": "https://networkselftest.ff.garena.com/api/",
  "login_failed_count": 2,
  "test_url": "",
  "core_url": "csoversea.castle.freefiremobile.com",
  "core_ip_list": [
    "0.0.0.0",
    "50.109.27.134",
    "129.226.2.163",
    "129.226.1.13",
    "129.226.1.16"
  ],
  "appstore_url": "http://play.google.com/store/apps/details?id=com.dts.freefiremax",
  "backup_appstore_url": "http://play.google.com/store/apps/details?id=com.dts.freefireth",
  "garena_login": false,
  "garena_hint": false,
  "gop_url": "",
  "gamevar": "var_name,comment,var_type,var_value,var_region,var_platform\nvar_name,comment,var_type,var_value,var_region,var_platform\nEnableVariableFFVoiceIDC,EnableVariableFFVoiceIDC,bool,false,,\nEnableYieldMutexDuringAsyncLoad,EnableYieldMutexDuringAsyncLoad,bool,false,,\nNinthProgressLoadingDuration,NinthProgressLoadingDuration,float,0,,\nEnableUGCScrollViewCulling,EnableUGCScrollViewCulling,bool,false,,\nReservedInt01,ReservedInt01,int,5,,\nNinthLevelPortalRadius,NinthLevelPortalRadius,float,20,,\nEnable2018ABstreamed,Enable2018ABstreamed,bool,false,,ios\nEnableAsyncCullResultsRelease,EnableAsyncCullResultsRelease,bool,false,,ios\nReservedInt02,ReservedInt02,int,30,,\nEnableGraphicsJobs,EnableGraphicsJobs,bool,true,,\nGraphicsJobsSyncPointValue,GraphicsJobsSyncPointValue,int,1,,\nHackEpicClothesToMaxLevel,HackEpicClothesToMaxLevel,bool,true,,\nEnableReportSystemTimeDelta,EnableReportSystemTimeDelta,bool,false,,",
  "remote_option_version": "optionallocres:50|optionalavatarres:708|optionalclothres:1150|optionalfootballres:47|optionalfullscreencgres:334|optionalhuntinggroundres:178|optionalinfection:121|optionalingameres:469|optionallobbyres:610|optionallonewolfres:77|optionallonewolfstrikeoutres:23|optionalludores:40|optionalmap1res:385|optionalmap2res:125|optionalmap4res:110|optionalmaphippores:90|optionalmapres:340|optionalnewblast:138|optionalpetres:848|optionalrushb:123|optionalrushingpetsres:88|optionalsnowduelres:59|optionaltrainingres:83|optionalugcres:537|optionalvoiceres:355|optionalwerewolves:173|optionalmapponyres:200|optionalsocialres:111|optionalwerunres:83|optionalugcoldparadiseres:32|optionalmultiregionres:25",
  "remote_option_version_astc": "optionallocres:50|optionalavatarres:711|optionalclothres:1150|optionalfootballres:38|optionalfullscreencgres:318|optionalhuntinggroundres:178|optionalinfection:116|optionalingameres:438|optionallobbyres:593|optionallonewolfres:139|optionallonewolfstrikeoutres:96|optionalludores:144|optionalmap1res:385|optionalmap2res:159|optionalmap4res:144|optionalmaphippores:92|optionalmapres:374|optionalnewblast:138|optionalpetres:848|optionalrushb:227|optionalrushingpetsres:192|optionalsnowduelres:59|optionaltrainingres:79|optionalugcres:507|optionalvoiceres:388|optionalwerewolves:277|optionalmapponyres:200|optionalsocialres:106|optionalwerunres:74|optionalugcoldparadiseres:32|optionalmultiregionres:26",
  "ggp_url": "gin.freefiremobile.com"
}
